TICKER_LIST = ['ZM','DOCU','WMT','AAPL','GE','TSLA','INTC','WORK','VVNT','EL.PA']
START_DATE = '20200101'
END_DATE = '20201231'
MAX_SHORT = 25
MAX_LONG = 50
DISPLAY_INDIVIDUAL_PLOTS = False #Bool to display plots