# The list of ticker strings to add to the portfolio
TICKER_LIST:
  - OXY
  - C
  - DIS
  - PYPL
  - DOCU
  - XOM
  - TSM
  - DEO
  - AMD
  - EL.PA

# The start and end dates strings, in 'YYYYMMDD' format
START_DATE: '2018-01-01'
END_DATE: '2022-12-31'

# The minimum and maximum (inclusive) 'short' to check between
MIN_SHORT: 2
MAX_SHORT: 120

# The minimum 'long' to check is the current 'short' in the loop plus this value
MIN_LONG_DIFFERENCE: 1
# The maximum 'long' to check
MAX_LONG: 200

# Whether or not to display the individual plots for each ticker
DISPLAY_INDIVIDUAL_PLOTS: True

# Whether or not to use multiprocessing to speed up the calculations
# (does not work on windows)
USE_MULTIPROCESSING: True
